/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jp_assignment;

import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author Carl
 */
public class StaffLogin extends javax.swing.JFrame {

    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
    }
//    
//        void validatedMessage()
//           {
//              JOptionPane.showMessageDialog(null, "Success, Welcome Administrator", "Success: " + "Access Granted", JOptionPane.INFORMATION_MESSAGE);
//
//           }
//    
//      void invalidMessage()
//        {
//            JOptionPane.showMessageDialog(null, "Failed Authentication. Please Try Again", "Error : " + "Authentication Failed", JOptionPane.ERROR_MESSAGE);
//            
//        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        systemTitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        inpPassword = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        inpUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblUsername1 = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Login");
        setBackground(new java.awt.Color(209, 225, 255));
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(209, 225, 255));
        bgPanel.setMinimumSize(new java.awt.Dimension(1130, 600));
        bgPanel.setPreferredSize(new java.awt.Dimension(1200, 600));
        bgPanel.setRequestFocusEnabled(false);
        bgPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bgPanelFocusGained(evt);
            }
        });
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        systemTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        systemTitle.setForeground(new java.awt.Color(255, 255, 255));
        systemTitle.setText("STAFF LOGIN");
        bgPanel.add(systemTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 740, 70));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(27, 89, 130));
        lblPassword.setText("Password");
        bgPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 140, 40));

        inpPassword.setForeground(new java.awt.Color(153, 153, 153));
        inpPassword.setText("     Please Enter Password");
        inpPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        inpPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpPasswordFocusLost(evt);
            }
        });
        inpPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpPasswordActionPerformed(evt);
            }
        });
        bgPanel.add(inpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 340, 50));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(27, 89, 130));
        lblUsername.setText("Username");
        bgPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 140, 40));

        inpUsername.setForeground(new java.awt.Color(153, 153, 153));
        inpUsername.setText("     Please Enter Username");
        inpUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        inpUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpUsernameFocusLost(evt);
            }
        });
        inpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpUsernameActionPerformed(evt);
            }
        });
        bgPanel.add(inpUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 340, 50));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(36, 101, 144));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        bgPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 120, 40));

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(27, 89, 130));
        lblUsername1.setText("Username");
        bgPanel.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 140, 40));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jp_assignment/Assets/bg.jpg"))); // NOI18N
        bgImage.setText("jLabel1");
        bgPanel.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(36, 101, 144));
        btnReset.setText("Reset");
        btnReset.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        btnReset.setBorderPainted(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        bgPanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpUsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inpUsernameActionPerformed

    private void inpPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpPasswordActionPerformed

    private void bgPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bgPanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bgPanelFocusGained

    private void inpUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpUsernameFocusGained
        // TODO add your handling code here:
        if(inpUsername.getText().equals("     Please Enter Username"))
        {
            inpUsername.setText("");
            inpUsername.setForeground(new Color(153,153,153)); 
        }
    }//GEN-LAST:event_inpUsernameFocusGained

    private void inpUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpUsernameFocusLost
        // TODO add your handling code here:
        if(inpUsername.getText().equals("     Please Enter Username"))
        {
            inpUsername.setText("");
            inpUsername.setForeground(new Color(153,153,153)); 
        }
    }//GEN-LAST:event_inpUsernameFocusLost

    private void inpPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpPasswordFocusGained
        // TODO add your handling code here:
        if(inpPassword.getText().equals("     Please Enter Password"))
        {
            inpPassword.setText("");
            inpPassword.setForeground(new Color(153,153,153)); 
        }
        
    }//GEN-LAST:event_inpPasswordFocusGained

    private void inpPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpPasswordFocusLost
        // TODO add your handling code here:
        if(inpPassword.getText().equals("     Please Enter Password"))
        {
            inpPassword.setText("");
            inpPassword.setForeground(new Color(153,153,153)); 
        }
    }//GEN-LAST:event_inpPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        
        
        
        String username, password, validation; 
        username = inpUsername.getText(); 
        password = inpPassword.getText(); 

       
        Login lg = new Login();
        lg.setUsername(username);
        lg.setUserPassword(password);
        
        validation = lg.accountValidation();
        
        
        
        if(validation == "True")
        {
            ActionClass ac = new ActionClass();
            ac.validatedMessage();
            dispose();
            ac.returnMenu();

        }   
        else
        {
            ActionClass invalid = new ActionClass();
            invalid.invalidMessage();
            
            inpUsername.setText("");
            inpPassword.setText("");
        }
        
        
        
        

       
    
    
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
            inpUsername.setText("");
            inpPassword.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField inpPassword;
    private javax.swing.JTextField inpUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel systemTitle;
    // End of variables declaration//GEN-END:variables
}
